### PR TITLE
adding system tests for data sharing framework

### PR DESCRIPTION
**Pull request by dbendele**
### What does this Pull Request accomplish?

- Adds basic system tests that establish loopback communication sustained for 60 s 
   - Compares received values to sent values

### Why should this Pull Request be merged?

Tests UDP and GE Reflective Memory components in a manner that fits with automated system tests

### What testing has been done?

UDP and GE Reflective Memory system tests executed on VS-ECO-HOST.

### CODE REVIEW

**Comment by dbendele** [comment]
### Note
An additional test for GE Reflective Memory is included (disabled) that tests for large block/transfer sizes; it is disabled until we enable scripting such that the system definition file that includes configuration of 1024000 bytes which would correspond to 128k channels. The subVI that performs the block DMA was tested and executes when run in the context of a PharLap target in a LabVIEW Project.

**Comment by dbendele** [comment]
###Note to Reviewers
You must manually open system definition files and save them in System Explorer prior running test* VIs. 
Refer to bug https://dev.azure.com/ni/DevCentral/_workitems/edit/1111318

**Comment by rtzoeller** [comment]
- [ ] Is the tolerance here needed? Can we just leave it unspecified (which forces the implementation to check equality directly)? I'm not sure how the reflective memory board serializes things.
image

- [ ] Is there a reason we would want to continue if a read/write times out?
image

- [ ] You can remove the "Minimum VeriStand Version" constant. We ought to update the default value for `Open VeriStand Connection.vi` to be 2017, but the reason this exists was for features which couldn't be tested in certain versions of VeriStand or LabVIEW. Since we only support 2017+ now, you can omit it entirely.
image

- [ ] The skipped tests will show up as failures. @Karl-G1 is that okay for your reporting?

**Comment by dbendele** [comment]
Serialization in DSF is byte array to string. Tolerance is an artifact of the many times I have been bitten by exact equality checks when comparing FP numbers. The bytes should be sent and received exactly. The test passed previously when tolerance was not specified. What is your recommendation?

**Comment by dbendele** [comment]
>- [ ] Is there a reason we would want to continue if a read/write times out?
We need to continue with deallocation and cleanup. We could add case structures within test(case(Read, case(Get Block, Block Read)), but that would reduce readability for sake of 1 s on a failed test

**Comment by rtzoeller** [comment]
> Serialization in DSF is byte array to string. Tolerance is an artifact of the many times I have been bitten by exact equality checks when comparing FP numbers. The bytes should be sent and received exactly. The test passed previously when tolerance was not specified. What is your recommendation?

If we are expecting exact equality, I'd prefer we write the test as such. If the test starts failing because we _aren't_ seeing exact equality, that gives us an opportunity to investigate if it's an issue with the plugin first.

I don't have a huge preference either way though, so if someone else disagrees I'm happy to change my mind.

**Comment by Karl-G1** [comment]
> The skipped tests will show up as failures. @Karl-G1 is that okay for your reporting?

@rtzoeller I'm fine with these reporting as skipped for now. We can discuss later what to do about tests that are likely to stay as manual execution and never be migrated to an ATS.

**Pull request merged**
