### PR TITLE
DSF Scripting API and Tests

### PR DESCRIPTION
**Pull request by dbendele**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-data-sharing-framework-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds scripting API for DSF custom device. Adds automated unit tests for this scripting API.

### Why should this Pull Request be merged?

Scripting is a requirement for all new custom devices to enable integrators to successfully configure high-channel custom devices in large systems where a UI is not practical.
 
### What testing has been done?

Automated unit tests are submitted with this pull request to validate all DSF scripting VIs.

### CODE REVIEW

**Comment by dbendele** [comment]
Note to Reviewers: recommend review of the scripting API, then reviewing the tests.

**Comment by rtzoeller** [comment]
- [ ] I would love to see proper error codes used here. The R+F API used stub error codes as well (single digit negative integers), but we never tracked the work to replace them. Can you either update the PR to accomplish this or create a work item to track it?

image

**Comment by rtzoeller** [comment]
Some of these are likely points for further discussion, rather than items which you should act on directly. If you agree with them, feel free to implement them, but otherwise I'm fine having a longer discussion.

- [ ] `NI VeriStand Enable System Explorer Update Buffer Wrapper.vi` & `NI VeriStand Commit System Explorer Update Buffer Wrapper.vi`: As you pointed out, error 7 is a relatively generic error code. I'd prefer if we didn't clear any incoming error 7s, e.g.

image

- [ ] `Find.vi`: This is another place where R+F does a poor job that we should deviate from (perhaps this PR will just be a running list of tech debt/bugs to go clean up in R+F 🤦‍♂️). The VeriStand API defines `0xFFFFFFFFFFFFFFFF` as the invalid node reference, not zero (see `NI VeriStand - Not a Ref.vi`).
I'd prefer to see this VI return that value if the custom device is not found, and also to have it return a boolean indicating if the custom device is found (like `NI VeriStand - Search for Item.vi`). Then `Add.vi` can consume the boolean, rather than knowing a bit too much about what the invalid integer value is.

- [ ] `Verify Node GUID Matches Data Sharing Framework GUID.vi`: This is another place where we are returning an generic error code.
IMO we should also consider using `Error Cluster From Error Code.vi` with the `show call chain?` terminal set to true to build these error codes. In my experience this can make troubleshooting significantly easier. @niphilj thoughts?

- [ ] `Get Data Server Options.vi` & `Set Data Server Options.vi`: The conversions between Hz and period make me a little uneasy, because we are going to lose precision in the process. 
image
image

- [ ] `Remove.vi`: Are there child sections or channels of the custom device which specify action VIs on delete that we're worried about not being called? Otherwise I don't see a need to remove all of the children of the custom device with `Delete All Children.vi`, I think we can just remove the top level node.

- [ ] `Set Debug Options.vi`: It's odd to me that the `Debug` string and property access aren't wrapped here, but are in `Get Debug Options.vi`.

- [ ] `Get Windows Debug Options.vi` & `Set Windows Debug Options.vi`: We seem to be writing the debugging options of the cluster as a group, but only reading one of them when retrieving. It seems like the custom device could end up in an unexpected state if it was configured through System Explorer and then queried back through the scripting API.

**Comment by dbendele** [comment]
>Get Data Server Options.vi & Set Data Server Options.vi: The conversions between Hz and period make me a little uneasy, because we are going to lose precision in the process.

The current implementation loses precision. There are only a finite set of frequencies where a _Set_ followed by a _Get_ will yield the same value. We could change the backend storage mechanism to store the server frequency as a double. Then, we would have to convert the frequency to a wait period where used. I think it is natural for users to configure the frequency. For data server frequencies less than 10 Hz, the loss in precision is insignificant. For higher data server frequencies, the error can be as much as 50 %. There are a number of values where we don't lose precision (i.e. 10 Hz); would you prefer that the scripting API help users choose good values, and/or return the actual data server frequency, and/or would you prefer that we reconcile the configuration and storage datatypes, and/or some other solution?

**Comment by dbendele** [comment]
>Remove.vi: Are there child sections or channels of the custom device which specify action VIs on delete that we're worried about not being called? Otherwise I don't see a need to remove all of the children of the custom device with Delete All Children.vi, I think we can just remove the top level node.

There is no Action VI on Delete that I am worried about. Does that mean that it is not good practice to remove all children of the CD before removing the CD?

**Comment by dbendele** [comment]
>Get Windows Debug Options.vi & Set Windows Debug Options.vi: We seem to be writing the debugging options of the cluster as a group, but only reading one of them when retrieving. It seems like the custom device could end up in an unexpected state if it was configured through System Explorer and then queried back through the scripting API.

There is no danger of the user setting the System Configuration and getting something inconsistent via the scripting API. I will review the code again to see why multiple fields are used to seemingly store the same information.

**Comment by rtzoeller** [comment]
> > Get Data Server Options.vi & Set Data Server Options.vi: The conversions between Hz and period make me a little uneasy, because we are going to lose precision in the process.
> 
> The current implementation loses precision. There are only a finite set of frequencies where a _Set_ followed by a _Get_ will yield the same value. We could change the backend storage mechanism to store the server frequency as a double. Then, we would have to convert the frequency to a wait period where used. I think it is natural for users to configure the frequency. For data server frequencies less than 10 Hz, the loss in precision is insignificant. For higher data server frequencies, the error can be as much as 50 %. There are a number of values where we don't lose precision (i.e. 10 Hz); would you prefer that the scripting API help users choose good values, and/or return the actual data server frequency, and/or would you prefer that we reconcile the configuration and storage datatypes, and/or some other solution?

I think this is a question for Darin.

**Comment by rtzoeller** [comment]
> > Remove.vi: Are there child sections or channels of the custom device which specify action VIs on delete that we're worried about not being called? Otherwise I don't see a need to remove all of the children of the custom device with Delete All Children.vi, I think we can just remove the top level node.
> 
> There is no Action VI on Delete that I am worried about. Does that mean that it is not good practice to remove all children of the CD before removing the CD?

Just removing the top level item seems simpler to me. There's no benefit to removing the children manually (that I'm aware of), so I'd prefer we keep the code as simple as possible.

**Comment by nidaring** [comment]
> The current implementation loses precision. There are only a finite set of frequencies where a Set followed by a Get will yield the same value.

In the spirit of 'not adding new functionality' but instead presenting better UI for the functionality that exists... Doug's proposed solution above that guides users to a set of good values by enumerating them in a ring control in the DSF UI seems like the best way forward. 

The scripting API would offer an input that would encourage users to make ring constants/controls with this same set of values.  The scripting API input would let a person wire up a numeric value of their own choosing outside of the set. Which could then lead to this problem of sloppy conversion; to mitigate Doug and I discussed having an 'actual data server frequency' output for users to monitor to see what the coerced frequency actually is.  I like it!

**Review by buckd — COMMENTED** [review]
- [x] `Set Show Threads.vi` and `Get Data Sharing Framework Measurement Options.vi` are in the Scripting API directory, but don't appear to be part of the library. Are these VIs used or can they be removed?

**Comment by rtzoeller** [comment]
- [ ] `Get Data Server Options.vi` skips on error anyways, so we should just call it from the error case in `Set Data Server Options.vi`.

image

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
