### PR TITLE
Set Reentrancy and Separate Compiled Code from Source

### PR DESCRIPTION
**Pull request by dbendele**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-data-sharing-framework-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Sets reentrancy to enable parallel operation of DSF applications that share a LV context (fixes Issue#15). Separates compiled code from source.

### Why should this Pull Request be merged?

Makes DSF robust in parallel operation and adds test to verify. Separating compiled code from source also prevents unnecessary file changes due to recompile.

### What testing has been done?

Run existing unit tests and new unit tests to verify functionality and reentrant execution.

### CODE REVIEW

**Comment by dbendele** [comment]
last commit only separates compiled code from source

**Comment by dbendele** [comment]
This file changed to fix an issue where only part of the previous string was being overwritten with current value:
https://github.com/ni/niveristand-data-sharing-framework-custom-device/pull/22/commits/120dc0c1ab12e5c81a8aa2dff97b2d08ec5fa74e#diff-24cd05e30543bc74987040324aa8ef6c

**Comment by dbendele** [comment]
Reentrancy Tests.lvclass and all owned VIs adds test to verify parallel execution.

**Comment by dbendele** [comment]
DSF Core.lvlib--Performance.lvclass--Write Timing Status.vi modified and replaced calling VI (Core/Classes/Performance/Update Timing.vi) other callers modified

**Comment by dbendele** [comment]
vast majority of changes relate to separation of compiled code from source and reentrancy settings of source VIs necessary to make new test case pass (still rely on build step to set reentrancy and inlining for remaining VIs)

**Recommend reviews focus on changes related to previous three comments.**

**Comment by niphilj** [comment]
> DSF Core.lvlib--Performance.lvclass--Write Timing Status.vi modified and replaced calling VI (Core/Classes/Performance/Update Timing.vi)

I have found that this is the case when the subVI isn't actually a dispatch VI and doesn't have access to the private data and no accessor exists. But if that's not the case, this pattern should be replaced as you described.

**Review by niphilj — COMMENTED** [review]
- [x] Should *Core/Tests/Classes/Reentrancy Tests/testDSFReentrancy.vi* be: Core/Tests/Classes/Reentrancy Tests/test DSFReentrancy.vi (with a space in the VI name between "test" and the rest of the name)?

**Comment by rtzoeller** [comment]
Please change the PR title to something other than the branch name.

**Comment by dbendele** [comment]
builds 8 and 9 aborted because we needed to free up build agents, and these changes had low risk

**Review by niphilj — APPROVED** [review]

**Pull request merged**
